---
- name: Install Hurl
  block:
    - name: Install Hurl
      apt:
        name: hurl
        state: present
        update_cache: yes

    - name: Create install directory
      file:
        path: "{{ hurl_install_dir }}"
        state: directory
        mode: "0755"

    - name: Create scenario directory
      file:
        path: "{{ hurl_install_dir }}/scenario"
        state: directory
        mode: "0755"

    - name: Add execution script
      template:
        src: templates/run-hurl.sh.j2
        dest: /opt/hurl/run-hurl.sh
        mode: "0755"

    - name: Copy Hurl configuration files
      copy:
        src: "{{ hurl_files }}"
        dest: "{{ hurl_files_dest }}"
        group: "root"
        owner: "root"
        mode: "0644"
        directory_mode: "0755"

    - name: Copy Hurl env file
      copy:
        src: "{{ hurl_env_file }}"
        dest: "{{ hurl_install_dir }}/scenario/"
        group: "root"
        owner: "root"
        mode: "0644"
        directory_mode: "0755"
